language: java
sudo: false

jdk:
  - openjdk11

script: ./travis.sh
env:
  - TEST=ci
matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
before_cache:
  - rm -rf $HOME/.m2/repository/org/sonarsource/analyzer-commons
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
  - secure: oUw9eE0o2CW4DaL9Nc2RmNK+6rqV5e5tmJagYs6oOG7Bfm0uSK5WAaWoElLx9RQ+5k7ypZwcNqxecFPAHqOPYoClPqxI8K2y66+xhIqkeB9+8ZxP0OZa00rhwY16UXyyVqUtVcCLGwhrFXhAjnJWxcnP3Ww6pUfeI8iSo+q5BvaGdSlJEu2t2rmSWRkHaarYeN6QtWG4v6zwn2kNvGhJhmWBARLauSXWlVI6KQdzMktgv70zHRqRyPnq3LDSvAKDZem0vEyGYLOL+j53VmAH8Z2C6re7iNC33u1pGIXKm2n1W/TXFQ3DBZZXmmA9zjD7+VRcl7fq0nJ3aR32+s9QulZY4Ho6w4s/QQnQoRwW3ywQi0xdMHLyYLm8o+l09GGcrnhmZyZM5BY5W9iF0j+3oGC5eysZY5yHW13RLGMDkBDHiXonek4Tle/fUZxcK4JYA9bPrnxHpy+c9IkEvuuQ16RZOOwkungDMmEcJoOlD1tu9R7/iOfywIC0uwNQDfpsMgI13YkpK1nJPLolDN/oZDQjA9+bBgzNNXVcVWfQbLbvETpEl2w45MVWN2JtZ80e6lKVnjvbL2sR0/biBFE167JVdYrF2VPUQTi5l+2cBuYuQgItawp3Lhvp4WoaJmEzGoFYvt7aPwsvhHuc+FNE6zExSzYUf+whZBeS7WfQu1o=
  on_start: always
