---
name: sonar-release
# This workflow is triggered when publishing a new github release
# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@f8fc75de307f2547eec9bf9e2628bf67080a3414 # 6.8.1
    with:
      publishToBinaries: true
      mavenCentralSync: true
      slackChannel: squad-corelang-releases

